### PR TITLE
Added ASUS TUF Gaming FX505DY to the list

### PR DESCRIPTION
**Pull request by jdoe0**

### CODE REVIEW

**Comment by T-vK** [comment]
Nice! Thank you so much for sharing, this is the first time I hear about GPU passthrough with a mobile AMD GPU.
I would love to hear what you had to do in order to get it to work and how flawless things work. 
Have you tried running demanding 3D applications yet? How do you connect to the VM? ( RDP, spice, LookingGlass, ... ? ) Are there any caveats?

**Comment by jdoe0** [comment]
> I would love to hear what you had to do in order to get it to work and how flawless things work.

It's actually pretty straightforward. I basically followed the instructions under section 1 - 3 of [this guide](https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF). That's enough to get the GPU to show up in the VM, but you'll have to supply a VBIOS to be able to actually use it. VBIOS extraction is a bit tricky as  easy methods (e.g. GPU-Z, ATIFlash, sysfs) all fail. I had to extract the UEFI image using `UEFIExtract` and locate the VBIOS with grep and a hex editor. I haven't played with the VM too much yet but everything seems to work as they should as far as I can tell.

>  Have you tried running demanding 3D applications yet? How do you connect to the VM? ( RDP, spice, LookingGlass, ... ? ) Are there any caveats?

The only demanding 3D application I tried so far is glmark2. The score I got was 2677, which I believe is a decent score for a mobile GPU. I connected to the VM using VNC for the test.

LookingGlass also kind of work. I can get the screen to show up on the host machine, but only if I disable SPICE using the `-s no` option. The client will complain that it can't connect to the SPICE server and refuse to start otherwise. I suspect that this is caused by some configuration issues on my part though.

> Sorry, I just realized that you wrote Works, but AMD driver fails with error 43.. I didn't even know that error 43 was a thing for non-Nvidia cards. Maybe this helps: https://www.reddit.com/r/VFIO/comments/9ws3qv/so_how_should_i_deal_with_code_43_but_for_amd/

I tried adding `ioh3420` as suggested in the post, but it didn't help. I also tried adding workarounds that people are using for Nvidia GPUs but those don't work either. I'll play around with it a bit more and let you know if I make any progress with the Windows VM.

**Comment by T-vK** [comment]
Thanks for the information. I had a lot of success with vbios-finder to extract VBIOSes from BIOS updates. Often it will find more than one VBIOS. Maybe you just extracted the wrong one? The installation is a bit tricky though. On Fedora I'm doing it like this: https://github.com/T-vK/MobilePassThrough/blob/master/utils/Fedora/30/vbios-finder-installer

Would you mind sharing your libvirt or virsh config?

**Comment by jdoe0** [comment]
> Often it will find more than one VBIOS. Maybe you just extracted the wrong one?

After extracting the UEFI image, I was actually able to identify 3 files that looks like VBIOSes by grepping for "ATOMBIOS". Using a hex editor, I found that each of them contains different AMD codenames: "Raven", "Picasso", and "Polaris". Since my dGPU's codename is Polaris, and I found no other file with that string in it, I'm pretty sure I got the right file.

> Would you mind sharing your libvirt or virsh config?

Here's my libvirt config: [w10.xml.txt](https://github.com/T-vK/gpu-passthrough.com/files/3447895/w10.xml.txt). I had to append `.txt` to the file name to get GitHub to accept it.

**Pull request merged**
